/**
 * microservice-posiljanje API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface ShipmentRequestDto {
  orderId: number;
  carrier: string;
  shippingCostCents: number;
  recipientName: string;
  street: string;
  houseNumber: string;
  city: string;
  postalCode: string;
  country: string;
}
