/**
 * microservice-posiljanje API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ShipmentStatus } from './shipmentStatus';

export interface ShipmentDto {
  id?: number;
  orderId?: number;
  trackingNumber?: string;
  carrier?: string;
  status?: ShipmentStatus;
  recipientName?: string;
  street?: string;
  houseNumber?: string;
  city?: string;
  postalCode?: string;
  country?: string;
  shippingCostCents?: number;
  createdAt?: string;
  updatedAt?: string;
}
export namespace ShipmentDto {}
