/**
 * microservice-posiljanje API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ShipmentStatus } from './shipmentStatus';

export interface TrackingStatusDto {
  trackingNumber?: string;
  externalStatus?: string;
  lastUpdated?: string;
  etaMinutes?: number;
  message?: string;
  shipmentStatus?: ShipmentStatus;
}
export namespace TrackingStatusDto {}
