/**
 * Nakup
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ElementDTO { 
    id_kosarica?: number;
    id_izdelek?: number;
    naziv?: string;
    cena?: number;
    kolicina?: number;
}

