/**
 * Katalog izdelkov
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface LastnostDTO {
  id_lastnost?: number;
  lastnost?: string;
  vrednost?: string;
}
