/**
 * Skladisce
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface RequestDTO {
  id_request?: string;
  type?: string;
  id_product?: number;
  id_user?: number;
  quantityAdd?: number;
  quantityRemove?: number;
}
