/**
 * Skladisce
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface ZalogaDTO {
  id_product?: number;
  stock?: number;
  reserved?: number;
}
