/**
 * microservice-narocila API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrderStatus } from './orderStatus';
import { OrderItemDto } from './orderItemDto';

export interface OrderDto {
  id?: number;
  userId?: number;
  recipientName?: string;
  street?: string;
  houseNumber?: string;
  city?: string;
  postalCode?: string;
  country?: string;
  totalPriceCents?: number;
  shippingCostCents?: number;
  paid?: boolean;
  paymentMethod?: string;
  shipmentId?: number;
  trackingNumber?: string;
  status?: OrderStatus;
  createdAt?: string;
  updatedAt?: string;
  items?: Array<OrderItemDto>;
}
export namespace OrderDto {}
