/**
 * microservice-narocila API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrderItemRequestDto } from './orderItemRequestDto';

export interface OrderRequestDto {
  userId: number;
  recipientName: string;
  street: string;
  houseNumber: string;
  city: string;
  postalCode: string;
  country: string;
  paymentMethod: string;
  paid: boolean;
  shippingCostCents: number;
  items: Array<OrderItemRequestDto>;
}
