/**
 * microservice-narocila API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrderStatus } from './orderStatus';

export interface UpdateStatusRequest {
  status?: OrderStatus;
}
export namespace UpdateStatusRequest {}
